apiVersion: v1
kind: Service
metadata:
  name: gowiki-svc-headless
  labels:
    app: gowiki
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    name: http
  selector:
    app: gowiki
---
apiVersion: v1
kind: Service
metadata:
  name: gowiki-svc
  labels:
    app: gowiki
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: gowiki
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: gowiki # has to match .spec.template.metadata.labels
  serviceName: "gowiki"
  replicas: 10 # by default is 1
  template:
    metadata:
      labels:
        app: gowiki # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: gowiki
        image: nathluu/gowiki:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
  #       volumeMounts:
  #       - name: www
  #         mountPath: /usr/share/gowiki/html
  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: "my-storage-class"
  #     resources:
  #       requests:
  #         storage: 1Gi